[build]
command = "npm run build"
publish = "dist/public"
functions = "netlify/functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]
included_files = ["db/schema.*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_ENV = "production"