[build]
command = "npm run build"
publish = "dist/public"
functions = "netlify/functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]
included_files = ["db/schema.*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_ENV = "production"

[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 5000
port = 8888
publish = "dist/public"