[build]
command = "npm run build"
publish = "dist/public"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]

[[redirects]]
from = "/api/hello"
to = "/.netlify/functions/hello"
status = 200
force = true

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--no-audit --no-fund"