[build]
command = "npm run build"
publish = "dist/public"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]
included_files = ["db/schema.*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[build.environment]
NODE_VERSION = "18.20.6"
NODE_ENV = "production"