[build]
command = "npm run build"
publish = "dist/public"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]
included_files = ["db/schema.ts"]

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true
headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true